language: r
cache: packages
warnings_are_errors: false


r:
  - oldrel
  - release


notifications:
  email:
    on_success: change
    on_failure: change
 
# for codecov
r_packages:
  - covr
  - devtools
 
  
os:
  - linux
  - osx

#jobs:
  #allow_failures:
    #- os: osx
  
  

after_success:
    - Rscript -e 'covr::codecov()'




