language: r
cache: maRs
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change
 
# for codecov
r_packages:
  - covr
  - devtools
 

sudo: required
  
os:
  - linux
  - osx

jobs:
  allow_failures:
    - os: osx
    
r_github_packages:
  - codecov/maRs

# only report coverage after build is successful
after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'covr::codecov()'
