before_install:
  - cd ./maRs
  - npm install
  - npm test 
  - npm run build


language: r
cache: packages
warnings_are_errors: true

before_deploy:
  - cd maRs



sudo: false

r:
  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change
 
# for codecov
r_packages:
  - covr
  - devtools
 
  
os:
  - linux
  - osx

jobs:
  allow_failures:
    - os: osx
    
r_github_packages:
  - codecov/maRs

script: test-all.R

# only report coverage after build is successful
after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'covr::codecov()'
