comment: false
language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'

ignore:
  - "maRs/R/windspeed.R"
  - "maRs/R/temperature.R"
  - "maRs/R/pressure.R"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
