comment: false
language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'

ignore:
  - "maRs/tests/testthat/test_windspeed.R"
  - "maRs/tests/testthat/test_pressure.R"
  - "maRs/tests/testthat/test_temperature.R"
  

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
